-- Run as the database owner or another role allowed to create tables and grant SELECT.
-- psql -X -v ON_ERROR_STOP=1 -h localhost -U postgres -d agentic_analyst -f sql/01_normalize_sales.sql
-- The whole import is one transaction: an error rolls back every change.
BEGIN;

-- Reruns may reuse tables made by this script. Refuse existing, unrelated objects.
DO $$
DECLARE
    existing_count integer;
    marked_count integer;
BEGIN
    SELECT COUNT(*), COUNT(*) FILTER (
        WHERE obj_description(c.oid, 'pg_class') = 'Agentic Data Analyst Phase 3.0'
    )
    INTO existing_count, marked_count
    FROM pg_catalog.pg_class AS c
    JOIN pg_catalog.pg_namespace AS n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relname IN ('customers', 'products', 'orders', 'order_items');

    IF existing_count <> 0 AND (existing_count <> 4 OR marked_count <> 4) THEN
        RAISE EXCEPTION 'Normalized table names already exist but were not all created by this migration.';
    END IF;

    -- The current source has one catalog price for each product name/category.
    IF EXISTS (
        SELECT 1
        FROM public.sales
        GROUP BY product_name, category
        HAVING COUNT(DISTINCT unit_price) <> 1
    ) THEN
        RAISE EXCEPTION 'A product has multiple source prices; review the product model before importing.';
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.customers (
    customer_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name varchar(100) NOT NULL,
    city varchar(100) NOT NULL,
    CONSTRAINT customers_name_city_key UNIQUE (customer_name, city)
);

CREATE TABLE IF NOT EXISTS public.products (
    product_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name varchar(150) NOT NULL,
    category varchar(100) NOT NULL,
    unit_price numeric(10, 2) NOT NULL,
    CONSTRAINT products_name_category_key UNIQUE (product_name, category)
);

CREATE TABLE IF NOT EXISTS public.orders (
    order_id integer PRIMARY KEY,
    customer_id integer NOT NULL,
    order_date date NOT NULL,
    payment_method varchar(50) NOT NULL,
    status varchar(30) NOT NULL,
    CONSTRAINT orders_customer_id_fkey
        FOREIGN KEY (customer_id) REFERENCES public.customers (customer_id)
);

CREATE TABLE IF NOT EXISTS public.order_items (
    order_item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10, 2) NOT NULL,
    discount_pct numeric(5, 2) NOT NULL,
    CONSTRAINT order_items_order_id_fkey
        FOREIGN KEY (order_id) REFERENCES public.orders (order_id),
    CONSTRAINT order_items_product_id_fkey
        FOREIGN KEY (product_id) REFERENCES public.products (product_id)
);

COMMENT ON TABLE public.customers IS 'Agentic Data Analyst Phase 3.0';
COMMENT ON TABLE public.products IS 'Agentic Data Analyst Phase 3.0';
COMMENT ON TABLE public.orders IS 'Agentic Data Analyst Phase 3.0';
COMMENT ON TABLE public.order_items IS 'Agentic Data Analyst Phase 3.0';

INSERT INTO public.customers (customer_name, city)
SELECT DISTINCT customer_name, city
FROM public.sales
ORDER BY customer_name, city
ON CONFLICT (customer_name, city) DO NOTHING;

INSERT INTO public.products (product_name, category, unit_price)
SELECT DISTINCT product_name, category, unit_price
FROM public.sales
ORDER BY product_name, category, unit_price
ON CONFLICT (product_name, category) DO NOTHING;

INSERT INTO public.orders (order_id, customer_id, order_date, payment_method, status)
SELECT s.order_id, c.customer_id, s.order_date, s.payment_method, s.status
FROM public.sales AS s
JOIN public.customers AS c
  ON c.customer_name = s.customer_name AND c.city = s.city
ON CONFLICT (order_id) DO NOTHING;

-- Existing sales has one row per order. A second item can be added later.
INSERT INTO public.order_items (order_id, product_id, quantity, unit_price, discount_pct)
SELECT s.order_id, p.product_id, s.quantity, s.unit_price, s.discount_pct
FROM public.sales AS s
JOIN public.products AS p
  ON p.product_name = s.product_name AND p.category = s.category
WHERE NOT EXISTS (
    SELECT 1 FROM public.order_items AS oi WHERE oi.order_id = s.order_id
)
ORDER BY s.order_id;

-- Confirm every source row is represented before committing.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM public.sales AS s
        WHERE NOT EXISTS (
            SELECT 1
            FROM public.orders AS o
            JOIN public.customers AS c ON c.customer_id = o.customer_id
            JOIN public.order_items AS oi ON oi.order_id = o.order_id
            JOIN public.products AS p ON p.product_id = oi.product_id
            WHERE o.order_id = s.order_id
              AND o.order_date = s.order_date
              AND o.payment_method = s.payment_method
              AND o.status = s.status
              AND c.customer_name = s.customer_name
              AND c.city = s.city
              AND p.product_name = s.product_name
              AND p.category = s.category
              AND p.unit_price = s.unit_price
              AND oi.quantity = s.quantity
              AND oi.unit_price = s.unit_price
              AND oi.discount_pct = s.discount_pct
        )
    ) THEN
        RAISE EXCEPTION 'A sales row does not match the normalized tables.';
    END IF;
END $$;

GRANT USAGE ON SCHEMA public TO analyst_agent;
GRANT SELECT ON public.customers, public.products, public.orders, public.order_items
    TO analyst_agent;

COMMIT;
